import Head from 'next/head';
import Navigation from '@/components/navigation';
import { Heading } from '@chakra-ui/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Favorite Cities App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/favicon.ico" />
      </Head>
      <Navigation />
      <Heading as="h1">I am the Home Page</Heading>
    </>
  );
}
